CREATE TABLE [dbo].[Menu](
	[ItemID] [nvarchar](10) NOT NULL,
	[ItemName] [nvarchar](100) NOT NULL,
	[ItemPrice] [decimal](10, 2) NULL,
	[ItemCategory] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Menu] ADD  DEFAULT ((10.00)) FOR [ItemPrice]