
USE [master]
GO

/****** Object:  Database [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF]    Script Date: 23/2/2025 10:28:57 PM ******/
CREATE DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FoodiePoint', FILENAME = N'C:\Users\heeth\OneDrive - Asia Pacific University\Degree 1st Year (Sem 2)\Object-oriented\Chef\Chef\Database\FoodiePoint.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FoodiePoint_log', FILENAME = N'C:\Users\heeth\OneDrive - Asia Pacific University\Degree 1st Year (Sem 2)\Object-oriented\Chef\Chef\Database\FoodiePoint_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET COMPATIBILITY_LEVEL = 150
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET ANSI_NULLS OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET ANSI_PADDING OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET ARITHABORT OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET AUTO_CLOSE ON
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET AUTO_SHRINK ON
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET  ENABLE_BROKER
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET RECOVERY SIMPLE
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET  MULTI_USER
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET DB_CHAINING OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET QUERY_STORE = OFF
GO

USE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF]
GO

/****** Object:  Table [dbo].[Feedbacks]    Script Date: 23/2/2025 10:28:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Halls]    Script Date: 23/2/2025 10:28:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Inventory]    Script Date: 23/2/2025 10:28:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Menu]    Script Date: 23/2/2025 10:28:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[OrderItem]    Script Date: 23/2/2025 10:28:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Orders]    Script Date: 23/2/2025 10:28:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Recipes]    Script Date: 23/2/2025 10:28:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Requests]    Script Date: 23/2/2025 10:28:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Reservations]    Script Date: 23/2/2025 10:28:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Users]    Script Date: 23/2/2025 10:28:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [C:\USERS\HEETH\ONEDRIVE - ASIA PACIFIC UNIVERSITY\DEGREE 1ST YEAR (SEM 2)\OBJECT-ORIENTED\CHEF\CHEF\DATABASE\FOODIEPOINT.MDF] SET  READ_WRITE
GO
